cmake_minimum_required(VERSION 3.21)
project(RuntimePackNetFx35Enabler LANGUAGES CXX)

add_executable(RuntimePack.NetFx35Enabler NetFx35Enabler.cpp)
target_compile_features(RuntimePack.NetFx35Enabler PRIVATE cxx_std_20)
target_compile_definitions(RuntimePack.NetFx35Enabler PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
set_target_properties(RuntimePack.NetFx35Enabler PROPERTIES WIN32_EXECUTABLE TRUE)
